
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOADING = 'LOADING'
export const DELETE_SUCCESS = 'DELETE_SUCCESS'
export const DELETE_FAIL = 'DELETE_FAIL'
export const ADD_SUCCESS = 'ADD_SUCCESS'
export const ADD_FAIL = 'ADD_FAIL'
export const EDIT_SUCCESS = 'EDIT_SUCCESS'
export const EDIT_FAIL = 'EDIT_FAIL'
export const TODOS_SUCCESS = 'TODOS_SUCCESS'
export const TODOS_FAIL = 'TODOS_FAIL'